const floorMockData = [
  {
    id: 1,
    companyId: 1,
    name: 'Ισόγειο',
    floorNumber: 0,
    zoneCount: 6,
    exitCount: 3,
    occupantCount: 28,
    floorPlanStatus: 'READY',
  },
  {
    id: 2,
    companyId: 1,
    name: '1ος όροφος',
    floorNumber: 1,
    zoneCount: 8,
    exitCount: 2,
    occupantCount: 24,
    floorPlanStatus: 'READY',
  },
  {
    id: 3,
    companyId: 1,
    name: '2ος όροφος',
    floorNumber: 2,
    zoneCount: 7,
    exitCount: 2,
    occupantCount: 20,
    floorPlanStatus: 'DRAFT',
  },
  {
    id: 4,
    companyId: 1,
    name: '3ος όροφος',
    floorNumber: 3,
    zoneCount: 5,
    exitCount: 2,
    occupantCount: 14,
    floorPlanStatus: 'NOT_STARTED',
  },

  {
    id: 5,
    companyId: 2,
    name: 'Ισόγειο',
    floorNumber: 0,
    zoneCount: 5,
    exitCount: 3,
    occupantCount: 22,
    floorPlanStatus: 'READY',
  },
  {
    id: 6,
    companyId: 2,
    name: '1ος όροφος',
    floorNumber: 1,
    zoneCount: 6,
    exitCount: 2,
    occupantCount: 18,
    floorPlanStatus: 'DRAFT',
  },
  {
    id: 7,
    companyId: 2,
    name: '2ος όροφος',
    floorNumber: 2,
    zoneCount: 4,
    exitCount: 2,
    occupantCount: 14,
    floorPlanStatus: 'NOT_STARTED',
  },
];

export default floorMockData;